# Generated by Django 6.0 on 2026-02-24 08:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APISecurityTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_url', models.URLField()),
                ('test_type', models.CharField(choices=[('auth', 'Authentication'), ('rate_limit', 'Rate Limiting'), ('injection', 'Injection Attacks'), ('cors', 'CORS Policy'), ('headers', 'Security Headers')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('testing', 'Test en cours'), ('completed', 'Complété'), ('failed', 'Erreur')], default='pending', max_length=20)),
                ('vulnerable', models.BooleanField(default=False)),
                ('issues_found', models.IntegerField(default=0)),
                ('test_details', models.JSONField(blank=True, default=dict)),
                ('recommendations', models.JSONField(blank=True, default=list)),
                ('duration', models.IntegerField(default=0, help_text='Durée du test en secondes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CVELookup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cve_id', models.CharField(max_length=20, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('severity', models.CharField(max_length=20)),
                ('cvss_score', models.FloatField(blank=True, null=True)),
                ('affected_versions', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('publication_date', models.DateField(blank=True, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-publication_date'],
            },
        ),
        migrations.CreateModel(
            name='NucleiScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('running', 'En cours'), ('completed', 'Complété'), ('failed', 'Erreur')], default='pending', max_length=20)),
                ('templates_used', models.IntegerField(default=0, help_text='Nombre de templates Nuclei utilisés')),
                ('vulnerabilities_found', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('info_count', models.IntegerField(default=0)),
                ('results_json', models.JSONField(blank=True, default=dict)),
                ('duration', models.IntegerField(default=0, help_text='Durée en secondes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PortScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('scanning', 'Scan en cours'), ('completed', 'Complété'), ('failed', 'Erreur')], default='pending', max_length=20)),
                ('open_ports_count', models.IntegerField(default=0)),
                ('closed_ports_count', models.IntegerField(default=0)),
                ('filtered_ports_count', models.IntegerField(default=0)),
                ('ports_data', models.JSONField(blank=True, default=dict)),
                ('os_detection', models.CharField(blank=True, max_length=255)),
                ('host_status', models.CharField(max_length=50)),
                ('duration', models.IntegerField(default=0, help_text='Durée du scan en secondes')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SSLTLSCert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('port', models.IntegerField(default=443)),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('checking', 'Vérification'), ('completed', 'Complété'), ('failed', 'Erreur')], default='pending', max_length=20)),
                ('cert_valid', models.BooleanField(default=False)),
                ('common_name', models.CharField(blank=True, max_length=255)),
                ('subject_alt_names', models.JSONField(blank=True, default=list)),
                ('issuer', models.CharField(blank=True, max_length=255)),
                ('not_before', models.DateTimeField(blank=True, null=True)),
                ('not_after', models.DateTimeField(blank=True, null=True)),
                ('serial_number', models.CharField(blank=True, max_length=255)),
                ('tls_versions', models.JSONField(blank=True, default=list)),
                ('cipher_suites', models.JSONField(blank=True, default=list)),
                ('vulnerable_ciphers', models.JSONField(blank=True, default=list)),
                ('ssl_rating', models.CharField(blank=True, max_length=2)),
                ('security_issues', models.JSONField(blank=True, default=list)),
                ('results_json', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IntegrationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target', models.CharField(max_length=255)),
                ('total_vulnerabilities', models.IntegerField(default=0)),
                ('critical_issues', models.IntegerField(default=0)),
                ('risk_level', models.CharField(choices=[('critical', 'Critique'), ('high', 'Élevé'), ('medium', 'Moyen'), ('low', 'Bas')], default='low', max_length=20)),
                ('report_generated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('nuclei_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.nucleiscan')),
                ('port_scan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.portscan')),
                ('ssl_check', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.ssltlscert')),
            ],
        ),
    ]
